version: '3.8'

services:
  app:
    build: .
    container_name: students_api_app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: students_api_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
